[package]
name = "sudoku_solver2"
version = "0.1.0"
authors = ["Hannah Ellis <hannahellis4242@gmail.com>"]

[dependencies]
itertools = "0.7.8"
clap = "2.32.0"
serde_json = "1.0.31"
valico = "2.2.0"
futures = "0.1.17"
hyper = "0.11.13"
